version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      # Lấy giá trị từ file .env (Docker Compose sẽ tự động tìm .env cùng thư mục)
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["5433:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    networks:
      - swiftroute-net

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks:
      - swiftroute-net

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    networks:
      - swiftroute-net

  api-gateway:
    build: ./services/api-gateway
    ports: ["8000:8000"]
    networks:
      - swiftroute-net
    depends_on:
      - auth-service

  auth-service:
    build: ./services/auth-service
    ports: ["8081:8081"]
    # Khai báo env_file để container Auth Service tự động tải toàn bộ biến từ file .env
    env_file:
      - .env
    environment:
      # DB_HOST trong mạng Docker Compose là tên container (tức là "postgres")
      - DB_HOST=postgres
      - DB_PORT=5432
      # Lấy trực tiếp từ file .env
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - swiftroute-net
    depends_on:
      - postgres
      - redis

networks:
  swiftroute-net:
    driver: bridge

volumes:
  pgdata: