server:
  port: 8000

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.ReactiveUserDetailsServiceAutoConfiguration
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              filters:
                - AddRequestHeader=X-Request-red, blue
              predicates:
                - Path=/api/auth/**

